export {
  DisplayLarge,
  DisplaySmall,
  HeadingH1,
  HeadingH2,
  HeadingH3,
  HeadingH4,
  HeadingH5,
  HeadingH6,
  OverlineLarge,
  OverlineMedium,
  OverlineXSmall,
  overlineXSmallCSS,
  ParagraphLarge,
  ParagraphMedium,
  paragraphMediumCSS,
  ParagraphSmall,
  paragraphSmallCSS,
  ParagraphXSmall,
  paragraphXSmallCSS,
} from "./Typography.styled";
export type {
  TypographyHeaderProps,
  TypographyOverlineProps,
  TypographyParagraphProps,
} from "./Typography.types";
