on:
  pull_request:
    branches: 
      - main
    
jobs:
  CI:
    name: CI
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          cache: 'yarn'

      - name: Install Deps
        run: yarn install
    
      - name: ESLint
        run: yarn eslint .

      - name: StyleLint
        run: yarn stylelint .

      - name: Test Website
        run: yarn jest --coverage

      - name: Coverage
        uses: andybelltree/lcov-reporter-action@v1.0.0
        with:
          title: Code Coverage
          filter-changed-files: true
          delete-old-comments: false
          lcov-file: ./coverage/lcov.info
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build
        run: yarn build
